# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: chat.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'chat.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nchat.proto\x12\x04\x63hat\":\n\x07Message\x12\x10\n\x08roomName\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t\"!\n\rCreateRoomReq\x12\x10\n\x08roomName\x18\x01 \x01(\t\"/\n\rCreateRoomRes\x12\x0f\n\x07success\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"\x0e\n\x0cListRoomsReq\"\x1d\n\x0cListRoomsRes\x12\r\n\x05rooms\x18\x01 \x03(\t\"1\n\x0bJoinRoomReq\x12\x10\n\x08roomName\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\"\'\n\tStreamMsg\x12\x1a\n\x03msg\x18\x01 \x01(\x0b\x32\r.chat.Message\"=\n\nSendMsgReq\x12\x10\n\x08roomName\x18\x01 \x01(\t\x12\x10\n\x08username\x18\x02 \x01(\t\x12\x0b\n\x03msg\x18\x03 \x01(\t2\xde\x01\n\x0b\x43hatService\x12\x36\n\ncreateRoom\x12\x13.chat.CreateRoomReq\x1a\x13.chat.CreateRoomRes\x12\x33\n\tlistRooms\x12\x12.chat.ListRoomsReq\x1a\x12.chat.ListRoomsRes\x12\x30\n\x08joinRoom\x12\x11.chat.JoinRoomReq\x1a\x0f.chat.StreamMsg0\x01\x12\x30\n\x07sendMsg\x12\x10.chat.SendMsgReq\x1a\x13.chat.CreateRoomResb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'chat_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGE']._serialized_start=20
  _globals['_MESSAGE']._serialized_end=78
  _globals['_CREATEROOMREQ']._serialized_start=80
  _globals['_CREATEROOMREQ']._serialized_end=113
  _globals['_CREATEROOMRES']._serialized_start=115
  _globals['_CREATEROOMRES']._serialized_end=162
  _globals['_LISTROOMSREQ']._serialized_start=164
  _globals['_LISTROOMSREQ']._serialized_end=178
  _globals['_LISTROOMSRES']._serialized_start=180
  _globals['_LISTROOMSRES']._serialized_end=209
  _globals['_JOINROOMREQ']._serialized_start=211
  _globals['_JOINROOMREQ']._serialized_end=260
  _globals['_STREAMMSG']._serialized_start=262
  _globals['_STREAMMSG']._serialized_end=301
  _globals['_SENDMSGREQ']._serialized_start=303
  _globals['_SENDMSGREQ']._serialized_end=364
  _globals['_CHATSERVICE']._serialized_start=367
  _globals['_CHATSERVICE']._serialized_end=589
# @@protoc_insertion_point(module_scope)
