# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import chat_pb2 as chat__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in chat_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatServiceStub(object):
    """Chat service with your Java function names
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.createRoom = channel.unary_unary(
                '/chat.ChatService/createRoom',
                request_serializer=chat__pb2.CreateRoomReq.SerializeToString,
                response_deserializer=chat__pb2.CreateRoomRes.FromString,
                _registered_method=True)
        self.listRooms = channel.unary_unary(
                '/chat.ChatService/listRooms',
                request_serializer=chat__pb2.ListRoomsReq.SerializeToString,
                response_deserializer=chat__pb2.ListRoomsRes.FromString,
                _registered_method=True)
        self.joinRoom = channel.unary_stream(
                '/chat.ChatService/joinRoom',
                request_serializer=chat__pb2.JoinRoomReq.SerializeToString,
                response_deserializer=chat__pb2.StreamMsg.FromString,
                _registered_method=True)
        self.sendMsg = channel.unary_unary(
                '/chat.ChatService/sendMsg',
                request_serializer=chat__pb2.SendMsgReq.SerializeToString,
                response_deserializer=chat__pb2.CreateRoomRes.FromString,
                _registered_method=True)


class ChatServiceServicer(object):
    """Chat service with your Java function names
    """

    def createRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def listRooms(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def joinRoom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sendMsg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'createRoom': grpc.unary_unary_rpc_method_handler(
                    servicer.createRoom,
                    request_deserializer=chat__pb2.CreateRoomReq.FromString,
                    response_serializer=chat__pb2.CreateRoomRes.SerializeToString,
            ),
            'listRooms': grpc.unary_unary_rpc_method_handler(
                    servicer.listRooms,
                    request_deserializer=chat__pb2.ListRoomsReq.FromString,
                    response_serializer=chat__pb2.ListRoomsRes.SerializeToString,
            ),
            'joinRoom': grpc.unary_stream_rpc_method_handler(
                    servicer.joinRoom,
                    request_deserializer=chat__pb2.JoinRoomReq.FromString,
                    response_serializer=chat__pb2.StreamMsg.SerializeToString,
            ),
            'sendMsg': grpc.unary_unary_rpc_method_handler(
                    servicer.sendMsg,
                    request_deserializer=chat__pb2.SendMsgReq.FromString,
                    response_serializer=chat__pb2.CreateRoomRes.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat.ChatService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('chat.ChatService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatService(object):
    """Chat service with your Java function names
    """

    @staticmethod
    def createRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/createRoom',
            chat__pb2.CreateRoomReq.SerializeToString,
            chat__pb2.CreateRoomRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def listRooms(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/listRooms',
            chat__pb2.ListRoomsReq.SerializeToString,
            chat__pb2.ListRoomsRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def joinRoom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/chat.ChatService/joinRoom',
            chat__pb2.JoinRoomReq.SerializeToString,
            chat__pb2.StreamMsg.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def sendMsg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/chat.ChatService/sendMsg',
            chat__pb2.SendMsgReq.SerializeToString,
            chat__pb2.CreateRoomRes.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
